services:
  # The Nginx Server
  nginx:
    image: nginx:alpine
    working_dir: /var/www
    container_name: my-nginx
    volumes:
      # 基本 conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  # The Database
  database:
    image: postgres:17-alpine
    container_name: my-pgsql
    volumes:
      - ../dbdata:/var/lib/postgresql/data
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_DB=kawa"
      - "POSTGRES_USER=kawa"
      - "POSTGRES_PASSWORD=kawa"
      - "PGUSER=kawa"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "kawa", "-U", "kawa"]
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 80s

  # rust sqlx cli migrate tool
  sqlx-cli:
    restart: "no"
    image: kawagami77/rust-sqlx-cli:latest
    working_dir: /app
    container_name: sqlx-cli
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./sqlx-cli/.env:/app/.env
      - ./sqlx-cli/migrations:/app/migrations
    depends_on:
      database:
        condition: service_healthy

  # https://microsoft.github.io/garnet/docs/welcome/releases#docker
  garnet:
    image: 'ghcr.io/microsoft/garnet'
    ulimits:
      memlock: -1
    # ports:
    #   - "6379:6379"
    container_name: garnet

volumes:
  dbdata:
