services:
  # The Nginx Server
  nginx:
    image: nginx:alpine
    working_dir: /var/www
    container_name: my-nginx
    volumes:
      # 基本 conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  # The Database
  database:
    image: postgres:17-alpine
    container_name: my-pgsql
    volumes:
      - ../dbdata:/var/lib/postgresql/data
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_DB=kawa"
      - "POSTGRES_USER=kawa"
      - "POSTGRES_PASSWORD=kawa"
      - "PGUSER=kawa"
    # ports:
    #     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "kawa", "-U", "kawa"]
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 80s

  # https://microsoft.github.io/garnet/docs/welcome/releases#docker
  garnet:
    image: 'ghcr.io/microsoft/garnet'
    ulimits:
      memlock: -1
    # ports:
    #   - "6379:6379"
    container_name: garnet

  vector:
    image: timberio/vector:latest-alpine # 使用 Vector 的官方 Docker 映像
    container_name: vector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro # 掛載您的組態檔
      - /var/run/docker.sock:/var/run/docker.sock:ro # 允許 Vector 存取 Docker socket 以讀取日誌
    command: ["--config", "/etc/vector/vector.yaml"] # 指定使用組態檔啟動 Vector
    depends_on:
      - api-server-axum
      - nginx
      - database
    restart: on-failure # 確保 Vector 在失敗時重啟
    logging:
      driver: "json-file" # 可以也讓 Vector 的日誌輸出到 json-file driver
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  dbdata:
