server {
    listen       80;
    listen  [::]:80;
    server_name  kawa.homes *.kawa.homes;
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;
    http2 on;
    server_name  kawa.homes *.kawa.homes;

    ssl_certificate     /etc/letsencrypt/live/kawa.homes/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kawa.homes/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        proxy_pass http://next-blog:3000;
    }
}
