server {
    listen       80;
    listen  [::]:80;
    server_name  kawa.homes *.kawa.homes;
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;
    server_name  kawa.homes *.kawa.homes;

    ssl_certificate     /etc/letsencrypt/live/kawa.homes/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kawa.homes/privkey.pem;

    location / {
        proxy_pass http://next-blog:3000;
    }
}
