services:
  nginx:
    volumes:
      - ./api-server-axum/prod.conf:/etc/nginx/conf.d/api-server-axum.conf
  api-server-axum:
    image: kawagami77/api-server:axum
    container_name: api-server-axum
    working_dir: /app
    volumes:
      - ./api-server-axum/.env:/app/.env
    depends_on:
      database:
        condition: service_healthy
