services:
  nginx:
    volumes:
      - ./api-server-axum/dev.conf:/etc/nginx/conf.d/api-server-axum.conf
  api-server-axum:
    image: kawagami77/api-server:axum
    container_name: api-server-axum
