server {
    listen       80;
    listen  [::]:80;
    server_name  axum.kawa.homes;
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;
    server_name  axum.kawa.homes;

    ssl_certificate     /etc/letsencrypt/live/kawa.homes/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kawa.homes/privkey.pem;

    location / {
        proxy_pass http://api-server-axum:3000;
        proxy_buffering off;            # 大檔直接流給 client，不落地 temp
        proxy_request_buffering off;

        # ws 協議
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
